version: "3.4"

services:
    inventory.api:
        image: webapi
        container_name: inventory.api
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__ExampleWebApiDbPostgres=Host=inventory.database;Port=5432;Database=inventory;Username=postgres;Password=postgres
        networks:
            - app-network
        ports:
            - "8080:8080"
        depends_on:
            - inventory.database
    
    inventory.database:
        image: postgres:17
        container_name: inventory.database
        environment:
            - POSTGRES_DB=inventory
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - app-network
        volumes:
            - "inventory-db:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
volumes:
    inventory-db:
networks:
    app-network: